AWSTemplateFormatVersion: 2010-09-09 
Description: CloudFormation template for s3 bucket
Parameters:
  BucketName:
    Description: Provide Bucket Name
    Type: String
Resources: 
  S3Bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
Outputs: 
  BucketName:
    Description: Bucket Created using this template.
    Value: !Ref S3Bucket
  BucketARN:
    Description: Bucket Created using this template.
    Value: !GetAtt S3Bucket.Arn 
    # Export: 
    #   Name: "BucketARN"
  
